#!/bin/bash

# File configuration
CFG_FILE="${CFG_FILE:-$HOME/.herorc}"

# Check for configuration file and source it
if [[ -e "$CFG_FILE" ]]; then
   source "$CFG_FILE"
fi

# Display help
usage() {
cat << EOF
USAGE:
  hero[ku] dmenu app command starter

   hero [ -n ]

OPTIONS:

   -n : start console in new terminal window

EOF
}

# Show an error message and print usage
error() {
   echo -e "\033[0;31m$1\033[0m"
   usage && exit 1
}

# Set flag options
while getopts "n" opt; do
   case "$opt" in
      n) new_window=true;;
      h) usage && exit 0;;
      *) error "Invalid flag.";;
   esac
done 2>/dev/null
shift "$((OPTIND-1))"

# Stylized dmenu
dmenu_fancy() {
  dmenu -b -i -l 10 -p : -fn 'Ttyp0-14' -nb \#101012 -sb \#66AABB -sf \#101012
}

app_name=$(printf "%s\n" "${APPS[@]}" | dmenu_fancy)

if [[ -z $app_name ]]; then
  exit 0
fi

command=$(printf "%s\n" "${COMMANDS[@]}" | dmenu_fancy)

if [[ -z $command ]]; then
  exit 0
fi

if [[ $new_window ]]; then
  st -e heroku run $command -a $app_name && exit 0
else
  heroku run $command -a $app_name && exit 0
fi
